# Test the real frontend, including the DSView log receiver. No USB needed.
function(check_case scenario expected_code expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "DSLCAP_TEST_SCENARIO=${scenario}" "${PROGRAM}"
        --scan --fw-dir "${FIRMWARE}"
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 10)
    if(NOT "${code}" STREQUAL "${expected_code}")
        message(FATAL_ERROR "${scenario}: expected ${expected_code}, got ${code}\n${out}\n${err}")
    endif()
    if(NOT err MATCHES "${expected_error}")
        message(FATAL_ERROR "${scenario}: missing diagnostic\n${err}")
    endif()
    if(scenario STREQUAL "init-fail")
        if(err MATCHES "FAKE cleanup" OR NOT err MATCHES "driver cleanup skipped")
            message(FATAL_ERROR "${scenario}: attempted unsafe partial-init cleanup\n${err}")
        endif()
    elseif(NOT err MATCHES "FAKE cleanup")
        message(FATAL_ERROR "${scenario}: missing driver cleanup\n${err}")
    endif()
    if(expected_code EQUAL 0)
        if(NOT out MATCHES "^2a0e:0034 DSLogic PLus bus=1 address=6 activated security=pass hdl=checked\n$")
            message(FATAL_ERROR "${scenario}: bad scan stdout: ${out}")
        endif()
        if(NOT err MATCHES "FAKE activation=2")
            message(FATAL_ERROR "${scenario}: HDL reopen not exercised")
        endif()
    elseif(NOT out STREQUAL "")
        message(FATAL_ERROR "${scenario}: error polluted stdout: ${out}")
    endif()
    message(STATUS "${scenario}: expected exit ${code}, diagnostic and cleanup verified")
endfunction()

check_case(success 0 "HDL check passed on reopen")
check_case(security-fail 6 "security check failed")
check_case(both-security 6 "security check failed")
check_case(no-security 6 "no explicit security-pass evidence")
check_case(no-security-reopen 6 "HDL verification reopen rejected")
check_case(fallback 5 "requested USB device must remain active")
check_case(last-error 5 "last_error=1")
check_case(info-fail 5 "initial activation failed")
check_case(activation-fail 5 "initial activation failed")
check_case(hdl-fail 5 "HDL verification reopen failed")
check_case(hdl-mismatch 5 "explicit HDL version check failed")
check_case(hdl-read-fail 5 "explicit HDL version check failed")
check_case(init-fail 5 "driver initialization failed")
check_case(list-fail 4 "cannot obtain device list")
check_case(no-device 4 "found 0")
check_case(wrong-pid 4 "found 0")
check_case(multiple 4 "found 2")
check_case(release-fail 7 "cannot release device")
check_case(cleanup-fail 7 "driver cleanup failed")

# Firmware validation must happen before even initializing/scanning USB.
string(REPEAT "x" 500 long_path)
foreach(directory IN ITEMS "${FIRMWARE}/nonexistent" "${long_path}" "")
    execute_process(COMMAND "${PROGRAM}" --scan --fw-dir "${directory}"
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 10)
    if(NOT code EQUAL 3 OR NOT out STREQUAL "" OR err MATCHES "FAKE init")
        message(FATAL_ERROR "invalid firmware path did not fail before init: ${code}\n${err}")
    endif()
endforeach()
message(STATUS "invalid, empty and 500-byte firmware paths rejected before driver init")
