function(capture_case scenario expected)
    set(output "${FIRMWARE}/../capture-test.raw")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "DSLCAP_TEST_SCENARIO=${scenario}" "${PROGRAM}" --fw-dir "${FIRMWARE}"
        --channels 0-7 --samplerate 25M --samples 73
        RESULT_VARIABLE code OUTPUT_FILE "${output}" ERROR_VARIABLE err TIMEOUT 10)
    if(NOT "${code}" STREQUAL "${expected}")
        message(FATAL_ERROR "${scenario}: expected ${expected}, got ${code}\n${err}")
    endif()
    if(NOT err MATCHES "FAKE cleanup")
        message(FATAL_ERROR "${scenario}: no cleanup\n${err}")
    endif()
    if(expected EQUAL 0)
        file(SIZE "${output}" size)
        if(NOT size EQUAL 99)
            message(FATAL_ERROR "${scenario}: wrong META plus finite payload size ${size}")
        endif()
    endif()
    message(STATUS "${scenario}: exit ${code}, cleanup verified")
endfunction()
capture_case(success 0)
capture_case(config-set-fail 8)
capture_case(config-read-fail 8)
capture_case(config-clamp 8)
capture_case(config-valid-count 8)
capture_case(config-enable-fail 8)
capture_case(config-enable-ignored 8)
capture_case(capture-start-fail 11)
capture_case(capture-overflow 10)
capture_case(capture-device-error 11)
capture_case(capture-detach 11)
capture_case(capture-speed 11)
capture_case(capture-short 13)
capture_case(capture-partial 13)
capture_case(capture-format 13)
capture_case(capture-status 13)
capture_case(capture-no-end 13)

function(cli_case expected)
    execute_process(COMMAND "${PROGRAM}" --fw-dir "${FIRMWARE}" ${ARGN}
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 10)
    if(NOT "${code}" STREQUAL "${expected}")
        message(FATAL_ERROR "CLI ${ARGN}: expected ${expected}, got ${code}\n${err}")
    endif()
    if(expected EQUAL 8 AND err MATCHES "FAKE init" AND NOT err MATCHES "FAKE cleanup")
        message(FATAL_ERROR "CLI ${ARGN}: initialized driver without cleanup")
    endif()
endfunction()
cli_case(8 --channels 0-7 --samplerate 50M --samples 73)
cli_case(8 --channels 0,1 --samplerate 60M --samples 73)
cli_case(8 --channels 0-7 --samplerate 3M --samples 73)
cli_case(8 --mode buffer --channels 0-15 --samplerate 100M --samples 16777217)
cli_case(8 --mode buffer --channels 15 --samplerate 200M --samples 73)
cli_case(2 --continuous --mode buffer)
cli_case(2 --samples 10 --time 1s)
cli_case(2 --samples 10 --continuous)
cli_case(2 --samples 0)
cli_case(2 --samplerate 25M)
cli_case(2 --time nan)
cli_case(2 --samples 73 --vth 2.6)
cli_case(2 --samples 73 --channels 0,0)
cli_case(0 --mode buffer --channels 0-7 --samplerate 100M --samples 73)
cli_case(0 --channels 0-11 --samplerate 25M --samples 73)
cli_case(0 --channels 0-15 --samplerate 20M --samples 73)
cli_case(0 --channels 0,3,9,15 --samplerate 25M --time 2.92us)
